micronaut:
  application:
    name: camundaMicronautKotlinExample
netty:
  default:
    allocator:
      max-order: 3
zeebe:
  client:
    cloud:
      defaultJobWorkerName: micronaut-kotlin-http-worker